project:
  type: website
  output-dir: _site
  resources:
    - R/

website:
  title: "AM Colonization Rate"
  navbar:
    background: primary
    search: false
    left:
      - text: "Calculator"
        href: index.qmd

filters:
  - webr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
